resources:
- name: repo
  type: git
  source:
    uri: https://github.com/chandrayarramreddy/gitrepo
    #uri: https://chandrayarramreddy:Chandr%4012@github.com/chandrayarramreddy/deploy-springboot-app-using-concourse-ci.git
    branch: master
    # Username: chandrayarramreddy
    # Password: Chandr@12
    # access_token: 6534cc4fd20ea1693bc7267652f877ae97417d53

# - name: s3-stored-jar
#   type: git


# - name: pcf-resource
#   type: cf
#   source:
#     api: https://api.run.pivotal.io
#     username: chandra.yarramreddy@gmail.com
#     password: Mypassword@1
#     organization: Devops
#     space: development
#     skip_cert_check: false

jobs:
- name: myjob
  plan:
  - get: repo
    trigger: true
  - task: simpletask
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
          - -exc
          - |
            cp -r repo changed-repo
            echo "This is my file content." > ./build/myapp-$(date +"%Y%m%d%H%S").txt
            git add .
            git commit -m "message"

            
      inputs:
      - name: repo

  - put: repo
    params: { repository: changed-repo }
# - name: deploy-app-to-pcf
#   public: true
#   plan:
#   #- get: s3-stored-jar
#   - get: gh-release
#     passed: [test-and-build]
#     trigger: true
# #  - get: source-code-from-github
#   - put: pcf-resource
#     params:
#       manifest: source-code-from-github/ci/manifest.yml
