cdresources:
- name: source-code-from-github
  type: git
  source:
    uri: https://github.com/chandrayarramreddy/deploy-springboot-app-using-concourse-ci.git
    #uri: https://chandrayarramreddy:Chandr%4012@github.com/chandrayarramreddy/deploy-springboot-app-using-concourse-ci.git
    branch: master
    # Username: chandrayarramreddy
    # Password: Chandr@12
    # access_token: 6534cc4fd20ea1693bc7267652f877ae97417d53

# - name: s3-stored-jar
#   type: git

- name: gh-release
  type: git
  source:
    uri: https://github.com/chandrayarramreddy/artifact-release.git 
    branch: master


# - name: pcf-resource
#   type: cf
#   source:
#     api: https://api.run.pivotal.io
#     username: chandra.yarramreddy@gmail.com
#     password: Mypassword@1
#     organization: Devops
#     space: development
#     skip_cert_check: false

jobs:
- name: test-and-build
  public: false
  plan:
    - get: source-code-from-github
      trigger: true
   # - get: s3-stored-jar
   # - get: gh-release
    - task: run-test-and-build-jar-file
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: java
            tag: 8
        inputs:
        - name: source-code-from-github
        outputs:
        - name: jar-file
        caches:
        - path: source-code-from-github/.m2
        run:
          path: source-code-from-github/ci/test-and-build.sh
   # - put: s3-stored-jar
    - put: gh-release
      params:
        file: jar-file/*.jar

# - name: deploy-app-to-pcf
#   public: true
#   plan:
#   #- get: s3-stored-jar
#   - get: gh-release
#     passed: [test-and-build]
#     trigger: true
# #  - get: source-code-from-github
#   - put: pcf-resource
#     params:
#       manifest: source-code-from-github/ci/manifest.yml

