resources:
- name: source-code-from-github
  type: git
  source:
    uri: https://github.com/chandrayarramreddy/deploy-springboot-app-using-concourse-ci-1.git
    branch: master

# - name: s3-stored-jar
#   type: s3
#   source:
#     bucket: eddytnk
#     region_name: us-east-2
#     regexp: jars/springboot-concourse-(.*)-SNAPSHOT.jar
#     access_key_id: ((AWSAccessKeyId))
#     secret_access_key: ((AWSSecretKey))

- name: pcf-resource
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: chandra.yarramreddy@gmail.com
    password: Mypassword@1
    organization: Devops
    space: development
    skip_cert_check: false

jobs:
- name: test-and-build
  public: true
  plan:
    - get: source-code-from-github
      trigger: true
    #- get: s3-stored-jar
    - task: run-test-and-build-jar-file
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: java
            tag: 8
        inputs:
        - name: source-code-from-github
        outputs:
        - name: jar-file
        caches:
        - path: source-code-from-github/.m2
        run:
          path: ./source-code-from-github/ci/test-and-build.sh
    # - put: s3-stored-jar
    #   params:
    #     file: jar-file/*.jar

# - name: deploy-app-to-pcf
#   public: true
#   plan:
  # - get: s3-stored-jar
  #   passed: [test-and-build]
  #   trigger: true
  # - get: source-code-from-github
    - put: pcf-resource
      params:
        manifest: source-code-from-github/ci/manifest.yml
        path: jar-file/*.jar

